# frozen_string_literal: true

# require "dependabot/python"
# require "dependabot/terraform"
# require "dependabot/elm"
# require "dependabot/docker"
# require "dependabot/git_submodules"
# require "dependabot/github_actions"
# require "dependabot/composer"
# require "dependabot/nuget"
# require "dependabot/gradle"
# require "dependabot/maven"
# require "dependabot/hex"
# require "dependabot/cargo"
# require "dependabot/go_modules"
# require "dependabot/npm_and_yarn"
# require "dependabot/dep"
# require "dependabot/bundler"


require "../../python/lib/dependabot/python"
require "../../terraform/lib/dependabot/terraform"
require "../../elm/lib/dependabot/elm"
require "../../docker/lib/dependabot/docker"
require "../../git_submodules/lib/dependabot/git_submodules"
require "../../github_actions/lib/dependabot/github_actions"
require "../../composer/lib/dependabot/composer"
require "../../nuget/lib/dependabot/nuget"
require "../../gradle/lib/dependabot/gradle"
require "../../maven/lib/dependabot/maven"
require "../../hex/lib/dependabot/hex"
require "../../cargo/lib/dependabot/cargo"
require "../../go_modules/lib/dependabot/go_modules"
require "../../npm_and_yarn/lib/dependabot/npm_and_yarn"
require "../../dep/lib/dependabot/dep"
require "../../bundler/lib/dependabot/bundler"
